name: Dependabot auto-merge

on: pull_request_target

jobs:
    check:
        runs-on: ubuntu-latest
        if: ${{ github.actor == 'dependabot[bot]' }}
        steps:
            - uses: actions/setup-node@v3
              with:
                  node-version: lts/*
            - uses: actions/checkout@v3
              with:
                  token: ${{ secrets.GH_OWNER_TOKEN }}
                  persist-credentials: false

            - name: Check Install dependencies
              run: npm it

            - name: Check builds works
              run: npm run build

    dependabot:
        needs: [check]
        runs-on: ubuntu-latest
        if: ${{ github.actor == 'dependabot[bot]' }}
        steps:
            - name: Dependabot metadata
              id: metadata
              uses: dependabot/fetch-metadata@v1.3.3
              with:
                  github-token: '${{ secrets.GH_OWNER_TOKEN }}'
            - name: Enable auto-merge for Dependabot PRs
              if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-patch'}}
              run: gh pr merge --auto --merge "$PR_URL"
              env:
                  PR_URL: ${{github.event.pull_request.html_url}}
                  GITHUB_TOKEN: ${{secrets.GH_OWNER_TOKEN }}
