name: Release

on: [workflow_dispatch]

jobs:
  test:
    name: Run tests
    uses: ./.github/workflows/test.yml

  release:
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.GH_OWNER_TOKEN }}
          persist-credentials: false

      - uses: oven-sh/setup-bun@v2

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: bun install

      - name: Build NPM package
        run: bun run build

      - name: Build CLI executable
        run: bun run compile

      - name: Semantic release
        uses: codfish/semantic-release-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_OWNER_TOKEN }}
          GIT_AUTHOR_NAME: "${{ github.actor }}"
          GIT_COMMITTER_NAME: "${{ github.actor }}"
