name: tests

on: [ workflow_call ]

jobs:
    conventional-commit-checker:
        name: Conventional Commit Checker
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
            - uses: webiny/action-conventional-commits@v1.4.2

    test:
        strategy:
            matrix:
                os: [ ubuntu-latest, macos-latest ]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v6
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
            - uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: bun install

            - name: Run tests
              run: bun run test
